### PR TITLE
switch from youtube to wistia

### PR DESCRIPTION
**Pull request by neerajdotname**
Switched from youtube to wistia but for some reason embed is not working.

@danishsatkut _a please look into it.

### CODE REVIEW

**Comment by danishsatkut** [comment]
SS:

Wistia

@neerajdotname _a Done.

**Comment by neerajdotname** [comment]
@danishsatkut _a can you switch other videos from youtube to wistia. For the wistia video ids refer to https://github.com/trinityradar/trinityradar-website/pull/36 .

**Comment by neerajdotname** [comment]
@danishsatkut can you take care of it and merge it tomorrow.

**Comment by danishsatkut** [comment]
Yes I will work on it tonight.

**Pull request merged**
